Fixed compilation error in MSVC with two-phase-lookup enabled
Two-phase lookup has been implemented by the MSVC team in Visual Studio 15.3, but is currently opt-in via `/permissive-`. Enabling it causes the compilation to fail at these two points with `error C2653: 'parser_t': is not a class or namespace name`.